import { type Puzzle } from "@/lib/puzzle";
import puzzlesData from "@/data/puzzles.json";

/**
 * Epoch for day numbering (UTC midnight, 2026-06-28 = launch day). The day
 * number is 1-based: launch day is #1, the next UTC day is #2, etc. Using UTC
 * means every player worldwide is on the same puzzle regardless of timezone.
 * To re-date the launch, change this to your desired day-#1 date.
 */
const EPOCH_UTC = Date.UTC(2026, 5, 28);
const MS_PER_DAY = 86_400_000;

/** 1-based puzzle number for the given instant (launch day = 1). */
export function getDayNumber(now: number = Date.now()): number {
  return Math.floor((now - EPOCH_UTC) / MS_PER_DAY) + 1;
}

/** Milliseconds remaining until the next UTC midnight (next puzzle). */
export function msUntilNextUtcMidnight(now: number = Date.now()): number {
  return MS_PER_DAY - ((now - EPOCH_UTC) % MS_PER_DAY);
}

/**
 * The daily puzzle pool, generated by the Phase 1 Wikidata pipeline
 * (`npm run build:data` -> src/data/puzzles.json). Each entry also carries
 * curation metadata (qid, fame, difficulty, needsReview) that the game itself
 * ignores; only the `Puzzle` fields are read at runtime.
 */
export const PUZZLES: Puzzle[] = puzzlesData as Puzzle[];

/** Deterministically selects the puzzle for a given (1-based) day number. */
export function getDailyPuzzle(dayNumber: number): Puzzle {
  const n = PUZZLES.length;
  const index = (((dayNumber - 1) % n) + n) % n; // day #1 -> PUZZLES[0]; safe for negatives
  return PUZZLES[index];
}

function firstParam(value: string | string[] | undefined): string | undefined {
  return Array.isArray(value) ? value[0] : value;
}

/**
 * Resolves the active day number, honoring dev-only URL overrides:
 *   ?day=N     absolute day number
 *   ?offset=N  relative to the real today (e.g. offset=1 = tomorrow)
 * Overrides are ignored in production builds, where the real UTC day is always
 * used.
 */
export function resolveDayNumber(searchParams?: {
  day?: string | string[];
  offset?: string | string[];
}): number {
  const today = getDayNumber();
  if (process.env.NODE_ENV === "production" || !searchParams) return today;

  const dayRaw = firstParam(searchParams.day);
  if (dayRaw !== undefined) {
    const day = Number.parseInt(dayRaw, 10);
    if (Number.isFinite(day)) return day;
  }

  const offsetRaw = firstParam(searchParams.offset);
  if (offsetRaw !== undefined) {
    const offset = Number.parseInt(offsetRaw, 10);
    if (Number.isFinite(offset)) return today + offset;
  }

  return today;
}
