import namesIndex from "@/data/names-index.json";

/**
 * Candidate names that power the guess autocomplete. Generated by the Phase 1
 * Wikidata pipeline (`npm run build:names` -> src/data/names-index.json): a
 * flat pool of well-known figures (every valid answer plus decoys) so any
 * answer is selectable while wrong-but-plausible guesses are also offered.
 */
export const FIGURE_NAMES: string[] = namesIndex as string[];
